# Generated by Django 5.0.14 on 2026-07-08 00:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('emploi_du_temps', '0002_initial'),
        ('enseignants', '0001_initial'),
        ('inscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinGenere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier_pdf', models.FileField(upload_to='bulletins/%Y/%m/', verbose_name='Fichier PDF')),
                ('genere_le', models.DateTimeField(auto_now_add=True, verbose_name='Généré le')),
                ('genere_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_generes', to=settings.AUTH_USER_MODEL, verbose_name='Généré par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_generes', to='inscriptions.inscription', verbose_name='Élève')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_generes', to='core.sessionvacances', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Bulletin généré',
                'verbose_name_plural': 'Bulletins générés',
                'ordering': ['-genere_le'],
            },
        ),
        migrations.CreateModel(
            name='BulletinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saisie_ouverte', models.BooleanField(default=False, verbose_name='Saisie des notes ouverte')),
                ('bulletin_generable', models.BooleanField(default=False, verbose_name='Bulletins générables')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_config', to='emploi_du_temps.niveau', verbose_name='Niveau / Classe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins_config', to='core.sessionvacances', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Configuration bulletin',
                'verbose_name_plural': 'Configurations bulletins',
                'unique_together': {('niveau', 'session')},
            },
        ),
        migrations.CreateModel(
            name='CoefficientMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coefficient', models.DecimalField(decimal_places=1, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.5')), django.core.validators.MaxValueValidator(Decimal('10.0'))], verbose_name='Coefficient')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='emploi_du_temps.matiere', verbose_name='Matière')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coefficients', to='emploi_du_temps.niveau', verbose_name='Niveau / Classe')),
            ],
            options={
                'verbose_name': 'Coefficient matière',
                'verbose_name_plural': 'Coefficients matières',
                'unique_together': {('matiere', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('20.0'))], verbose_name='Note /20')),
                ('observation', models.TextField(blank=True, verbose_name='Observation')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_saisies', to='enseignants.enseignant', verbose_name='Enseignant')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='inscriptions.inscription', verbose_name='Élève')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='emploi_du_temps.matiere', verbose_name='Matière')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.sessionvacances', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['matiere__nom'],
                'unique_together': {('inscription', 'matiere', 'session')},
            },
        ),
    ]
