# Generated by Django 5.0.14 on 2026-07-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatureEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('niveau_etude', models.CharField(choices=[('BAC', 'Baccalauréat'), ('LICENCE1', 'Licence 1'), ('LICENCE2', 'Licence 2'), ('LICENCE3', 'Licence 3'), ('MASTER1', 'Master 1'), ('MASTER2', 'Master 2'), ('DOCTORAT', 'Doctorat'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Niveau d'études")),
                ('experience', models.TextField(blank=True, verbose_name='Expérience')),
                ('cv_fichier', models.FileField(blank=True, null=True, upload_to='cv_candidatures/', verbose_name='CV (fichier)')),
                ('motivation', models.TextField(verbose_name='Lettre de motivation')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('ACCEPTE', 'Acceptée'), ('REFUSE', 'Refusée')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
            ],
            options={
                'verbose_name': 'Candidature enseignant',
                'verbose_name_plural': 'Candidatures enseignants',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
