# Generated by Django 5.0.14 on 2026-07-07 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0001_initial'),
        ('emploi_du_temps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatureenseignant',
            name='matieres_souhaitees',
            field=models.ManyToManyField(to='emploi_du_temps.matiere', verbose_name='Matières souhaitées'),
        ),
        migrations.AddField(
            model_name='candidatureenseignant',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
    ]
