# Generated by Django 5.0.14 on 2026-07-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SessionVacances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom de la session')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('annee', models.PositiveIntegerField(verbose_name='Année')),
                ('est_active', models.BooleanField(default=False, verbose_name='Session active')),
                ('frais_inscription', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name="Frais d'inscription (FCFA)")),
                ('tolerance_retard_minutes', models.PositiveIntegerField(default=10, verbose_name='Tolérance de retard (minutes)')),
            ],
            options={
                'verbose_name': 'Session de vacances',
                'verbose_name_plural': 'Sessions de vacances',
                'ordering': ['-date_debut'],
            },
        ),
    ]
