# Generated by Django 5.0.14 on 2026-07-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi')], max_length=10, verbose_name='Jour')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('salle', models.CharField(blank=True, max_length=50, verbose_name='Salle')),
            ],
            options={
                'verbose_name': "Créneau d'emploi du temps",
                'verbose_name_plural': "Créneaux d'emploi du temps",
                'ordering': ['session', 'jour', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière')),
                ('niveau_concerne', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], max_length=20, verbose_name='Niveau concerné')),
                ('couleur_badge', models.CharField(default='#0048AE', max_length=7, verbose_name='Couleur du badge (hex)')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du niveau / classe')),
                ('cycle', models.CharField(choices=[('PRIMAIRE', 'Primaire'), ('COLLEGE', 'Collège'), ('LYCEE', 'Lycée')], max_length=20, verbose_name='Cycle')),
                ('frais_inscription', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name="Frais d'inscription (FCFA)")),
            ],
            options={
                'verbose_name': 'Niveau / Classe',
                'verbose_name_plural': 'Niveaux / Classes',
                'ordering': ['cycle', 'nom'],
            },
        ),
    ]
