# Generated by Django 5.0.14 on 2026-07-07 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('emploi_du_temps', '0001_initial'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emploidutemps',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='enseignants.enseignant', verbose_name='Enseignant'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='core.sessionvacances', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='emploi_du_temps.matiere', verbose_name='Matière'),
        ),
        migrations.AddField(
            model_name='emploidutemps',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creneaux', to='emploi_du_temps.niveau', verbose_name='Niveau / Classe'),
        ),
        migrations.AddConstraint(
            model_name='emploidutemps',
            constraint=models.UniqueConstraint(fields=('session', 'jour', 'heure_debut', 'enseignant'), name='unique_enseignant_creneau_simultane'),
        ),
    ]
