# Generated by Django 5.0.14 on 2026-07-07 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('enseignants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200, verbose_name='Libellé')),
                ('categorie', models.CharField(choices=[('FOURNITURES', 'Fournitures'), ('LOGIQUE', 'Logistique'), ('COMMUNICATION', 'Communication'), ('RESTAURATION', 'Restauration'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Catégorie')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('date_depense', models.DateField(verbose_name='Date de la dépense')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs_depenses/', verbose_name='Justificatif')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='Salaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_personnel', models.CharField(choices=[('ENSEIGNANT', 'Enseignant'), ('COMITE', 'Comité')], default='ENSEIGNANT', max_length=15, verbose_name='Type de personnel')),
                ('nombre_heures_effectuees', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name="Nombre d'heures effectuées")),
                ('taux_horaire', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Taux horaire (FCFA)')),
                ('montant_brut', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant brut (FCFA)')),
                ('montant_deja_verse', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Montant déjà versé (FCFA)')),
                ('statut', models.CharField(choices=[('CALCULE', 'Calculé'), ('PARTIELLEMENT_PAYE', 'Partiellement payé'), ('PAYE', 'Payé')], default='CALCULE', max_length=20, verbose_name='Statut')),
                ('date_calcul', models.DateTimeField(auto_now_add=True, verbose_name='Date de calcul')),
                ('date_versement', models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier versement')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='enseignants.enseignant', verbose_name='Enseignant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='core.sessionvacances', verbose_name='Session')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to=settings.AUTH_USER_MODEL, verbose_name='Bénéficiaire')),
            ],
            options={
                'verbose_name': 'Salaire',
                'verbose_name_plural': 'Salaires',
                'ordering': ['-date_calcul'],
            },
        ),
        migrations.CreateModel(
            name='VersementSalaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('date_versement', models.DateTimeField(auto_now_add=True, verbose_name='Date du versement')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement bancaire')], default='ESPECES', max_length=15, verbose_name='Mode de paiement')),
                ('salaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versements', to='finances.salaire', verbose_name='Salaire')),
                ('verse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versements_effectues', to=settings.AUTH_USER_MODEL, verbose_name='Versé par')),
            ],
            options={
                'verbose_name': 'Versement de salaire',
                'verbose_name_plural': 'Versements de salaire',
                'ordering': ['-date_versement'],
            },
        ),
        migrations.AddConstraint(
            model_name='salaire',
            constraint=models.UniqueConstraint(fields=('utilisateur', 'session'), name='unique_salaire_utilisateur_session'),
        ),
    ]
