# Generated by Django 5.0.14 on 2026-07-07 23:32

import apps.enseignants.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidatures', '0001_initial'),
        ('emploi_du_temps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UID du QR code')),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to=apps.enseignants.models.qr_code_upload_path, verbose_name='Image du QR code')),
                ('taux_horaire', models.DecimalField(decimal_places=0, default=1000, max_digits=10, verbose_name='Taux horaire (FCFA)')),
                ('date_activation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'activation")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Enseignant actif')),
                ('candidature_origine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignant_cree', to='candidatures.candidatureenseignant', verbose_name="Candidature d'origine")),
                ('matieres', models.ManyToManyField(to='emploi_du_temps.matiere', verbose_name='Matières enseignées')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure_scan', models.DateTimeField(auto_now_add=True, verbose_name='Heure du scan')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('PRESENT', 'Présent (validé)'), ('RETARD', 'Retard (validé)'), ('ABSENT', 'Absent')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('creneau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='emploi_du_temps.emploidutemps', verbose_name='Créneau')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='enseignants.enseignant', verbose_name='Enseignant')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'ordering': ['-date', '-heure_scan'],
            },
        ),
        migrations.AddConstraint(
            model_name='presence',
            constraint=models.UniqueConstraint(fields=('enseignant', 'creneau', 'date'), name='unique_presence_par_creneau_jour'),
        ),
    ]
