# Generated by Django 5.0.14 on 2026-07-07 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('emploi_du_temps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleve', models.CharField(max_length=100, verbose_name="Nom de l'élève")),
                ('prenom_eleve', models.CharField(max_length=100, verbose_name="Prénom de l'élève")),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('nom_parent', models.CharField(max_length=200, verbose_name='Nom du parent / tuteur')),
                ('telephone_parent', models.CharField(max_length=20, verbose_name='Téléphone du parent')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut_paiement', models.CharField(choices=[('IMPAYE', 'Impayé'), ('PARTIEL', 'Partiel'), ('PAYE', 'Payé')], default='IMPAYE', max_length=10, verbose_name='Statut du paiement')),
                ('montant_du', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Montant dû (FCFA)')),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Montant payé (FCFA)')),
                ('matieres_choisies', models.ManyToManyField(to='emploi_du_temps.matiere', verbose_name='Matières choisies')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='emploi_du_temps.niveau', verbose_name='Niveau / Classe')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='core.sessionvacances', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Inscription élève',
                'verbose_name_plural': 'Inscriptions élèves',
                'ordering': ['-date_inscription'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Montant (FCFA)')),
                ('methode', models.CharField(choices=[('ESPECES', 'Espèces'), ('FEDAPAY_MOBILE_MONEY', 'FedaPay Mobile Money')], max_length=25, verbose_name='Méthode de paiement')),
                ('reference_fedapay', models.CharField(blank=True, max_length=100, null=True, verbose_name='Référence FedaPay')),
                ('date_paiement', models.DateTimeField(auto_now_add=True, verbose_name='Date de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ECHOUE', 'Échoué')], default='EN_ATTENTE', max_length=15, verbose_name='Statut')),
                ('enregistre_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('inscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='inscriptions.inscription', verbose_name='Inscription')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
